FROM centos:centos6.10

# add repos and update paths  - https://www.getpagespeed.com/server-setup/how-to-fix-yum-after-centos-6-went-eol

RUN curl https://www.getpagespeed.com/files/centos6-eol.repo --output /etc/yum.repos.d/CentOS-Base.repo && \
    curl https://www.getpagespeed.com/files/centos6-epel-eol.repo --output /etc/yum.repos.d/epel.repo && \
    curl https://www.getpagespeed.com/files/centos6-scl-eol.repo --output /etc/yum.repos.d/CentOS-SCLo-scl.repo && \
    curl https://www.getpagespeed.com/files/centos6-scl-rh-eol.repo --output /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo && \
    sed -i 's%^mirrorlist%#mirrorlist%g' /etc/yum.repos.d/* && \
    sed -i 's%#baseurl=http://mirror.centos.org%baseurl=https://vault.centos.org%g' /etc/yum.repos.d/* && \
    sed -i 's,http://vault.centos.org,https://vault.centos.org,g' /etc/yum.repos.d/* 




# add explicit http proxy manually if necessary - uncomment below
# ENV HTTP_PROXY="http://proxy.tch.harvard.edu:3128"


############################
# Install dependencies
############################

# update and install basic tools (gcc, gcc-c, make)
RUN yum update -y && \
    yum groupinstall -y 'Development Tools'

# install epel release and yum utils. 
RUN yum install -y yum-utils \
                    epel-release \
                    zlib-devel \
                    ncurses-devel \
                    gdbm-devel

# install dependencies whose versions do not match (to ubuntu equivalents in crkit)                    
RUN yum install -y nss-devel \
                    openssl-devel \
                    freetype-devel \
                    qt5-qtbase-devel \
                    qt5-qtbase-gui \
                    atlas-devel \                                        
                    openjpeg-devel openjpeg-libs libjpeg-turbo-devel

# install dependencies 
RUN yum install -y readline-devel \
                    libffi-devel \
                    wget \
                    git \
                    perl \
                    gperf \
                    bison \
                    flex \
                    unzip \
                    cmake \
                    gflags-devel \
                    eigen3-devel \
                    suiteparse \
                    tbb-devel \
                    fontconfig-devel \
                    lz4-devel \
                    xz-lzma-compat \
                    netcdf-devel \
                    libogg-devel \
                    libtheora-devel \
                    libpng-devel \                   
                    libtiff-devel \
                    jsoncpp-devel \
                    compat-expat1 \
                    glew-devel \
                    hdf5-devel \
                    qt5-qtx11extras-devel \
                    qt5-qtbase \
                    qt5-qttools \
                    libXt-devel \
                    libxml2-devel \
                    sqlite-devel
                    

# install python dependencies 
RUN yum install -y --nogpgcheck python34 python34-devel \
                                rh-python34-python-devel \
                                rh-python34-python-pip

# install xcb tools (versions do not match)
RUN yum install -y libxcb-devel libXinerama


####################
# dependencies that do not exist on centos6 as preloaded rpms 
####################

# -- libgoogle-glog-dev >> # not found - only available with centos7 - https://centos.pkgs.org/7/epel-x86_64/glog-0.3.3-8.el7.x86_64.rpm.html

# -- libproj-dev >>  # not found - only available with centos7 - https://centos.pkgs.org/7/epel-x86_64/proj-4.8.0-4.el7.x86_64.rpm.html, 

# -- libdouble-conversion-dev # not found - only available with centos7 - https://centos.pkgs.org/7/epel-x86_64/double-conversion-2.0.1-3.el7.x86_64.rpm.html

# -- libnetcdf-cxx-legacy-dev # not found - only available with centos7 - https://centos.pkgs.org/7/epel-x86_64/netcdf-cxx-4.2-8.el7.x86_64.rpm.html

# --libswscale-dev # not found - only available with centos7 - https://centos.pkgs.org/7/cheese-x86_64/libswscale-devel-2.6.2-2.x86_64.rpm.html



###############
# Local copy of dependencies: vtk, itk, nlopt, tclap 
###############

# add dependencies 
RUN mkdir -p /home/ch155417/moti/gsl/ /home/ch169807/moti/itkNLOPTOptimizers/ /home/ch155417/moti/nlopt-2.2/ /home/ch169807/Software/tclap-1.2.1 
COPY ./libs/gsl /home/ch155417/moti/gsl
COPY ./libs/itkNLOPTOptimizers /home/ch169807/moti/itkNLOPTOptimizers
COPY ./libs/nlopt-2.2 /home/ch155417/moti/nlopt-2.2
COPY ./libs/tclap-1.2.1 /home/ch169807/Software/tclap-1.2.1


# add vtk and itk 
RUN mkdir -p /opt/x86_64/pkgs/itk/4.3.1/ /opt/x86_64/pkgs/vtk/5.8.0
COPY ./libs/itk/4.3.1 /opt/x86_64/pkgs/itk/4.3.1
COPY ./libs/vtk/5.8.0 /opt/x86_64/pkgs/vtk/5.8.0

###############
# Add scim code
###############

# add scim code 
RUN mkdir -p /scim
COPY ./scim_cpp/dwi_bootstrap /scim

###############
# clean yum cache 
###############
RUN yum makecache fast && yum clean all 

###############
# Build scim code - how? 
###############
RUN mkdir -p /opt/x86_64/pkgs/itk/3.20.0 /opt/x86_64/pkgs/vtk/current/
COPY ./libs/itk/3.20.0 /opt/x86_64/pkgs/itk/3.20.0
COPY ./libs/vtk/6.1.0 /opt/x86_64/pkgs/vtk/current

