FROM centos6_crl

# install python dependencies 
RUN yum install -y --nogpgcheck python34 python34-devel

RUN yum install -y libuuid-devel

RUN mkdir /itkbuildenv && cd /itkbuildenv && \
    git clone -b release-3.20 https://github.com/InsightSoftwareConsortium/ITK.git ITK && \
    cd ITK && mkdir build && cd build && \
    cmake3 -DCMAKE_INSTALL_PREFIX=/opt/itk \
    -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" \
    -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
    -DBUILD_EXAMPLES:BOOL=OFF \
    -DBUILD_TESTING:BOOL=OFF \
    -DBUILD_SHARED_LIBS:BOOL=ON \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG" \
    .. && \
    make -j 4 && make install 
    
RUN mkdir /nloptbuildenv && cd /nloptbuildenv && \
    git clone https://github.com/stevengj/nlopt nlopt && \
    cd nlopt && \
    mkdir build && cd build && \
    cmake3 -DCMAKE_INSTALL_PREFIX=/opt/nlopt \
    -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" \
    -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
    -DCMAKE_BUILD_TYPE:STRING=Release \
    -DBUILD_SHARED_LIBS:STRING=OFF \
    -DCMAKE_CXX_FLAGS_RELEASE:STRING="-O3 -DNDEBUG" \
    .. && \
    make -j 4 && make install    
  
    
    
    
    
RUN mkdir /vtkbuildenv && cd /vtkbuildenv && \
    git clone https://gitlab.kitware.com/vtk/vtk.git VTK && \
    cd VTK && \
    git checkout 82840f008383c7767c693edb82ddddab1d9f9a51 && \
    mkdir build && cd build && \
    PYTHON="$(which python3)" && PREFIX=/usr/ && \
    export PYTHON_INCLUDE_DIR=$($PYTHON -c "from distutils import sysconfig; print(sysconfig.get_python_inc())") && \
    export PYTHON_LIBRARY=$(ldd $PYTHON | grep $PREFIX | grep 'libpython.*\.so' | cut -d' ' -f3) && \
    cmake -DCMAKE_INSTALL_PREFIX=/opt/vtk \
      -DCMAKE_BUILD_TYPE:STRING=Release \
      -DBUILD_SHARED_LIBS:BOOL=OFF \
      -DCMAKE_INSTALL_RPATH="${CMAKE_INSTALL_PREFIX}/lib" \
          -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE \
          -DVTK_BUILD_DOCUMENTATION=OFF \
          -DVTK_BUILD_TESTING=OFF \
          -DVTK_BUILD_EXAMPLES=OFF \
          -DBUILD_USER_DEFINED_LIBS:BOOL=OFF \
          -DVTK_LEGACY_REMOVE=ON \
          -DVTK_ANDROID_BUILD=OFF \
          -DVTK_IOS_BUILD=OFF \
          -DVTK_EXTRA_COMPILER_WARNINGS=OFF \
          -DVTK_GROUP_ENABLE_Views=NO \
          -DVTK_GROUP_ENABLE_Web=NO \
          -DVTK_GROUP_ENABLE_Imaging=NO \
          -DVTK_GROUP_ENABLE_Qt=DONT_WANT \
          -DVTK_GROUP_ENABLE_Rendering=DONT_WANT \
          -DVTK_PYTHON_VERSION=3 \
          -DVTK_ENABLE_WRAPPING=ON \
          -DVTK_WRAP_PYTHON=ON \
          -DVTK_WRAP_JAVA=OFF \
          -DVTK_USE_LARGE_DATA=OFF \
          -DCMAKE_C_FLAGS=-DGLX_GLXEXT_LEGACY \
          -DCMAKE_CXX_FLAGS=-DGLX_GLXEXT_LEGACY \
          -DPYTHON_EXECUTABLE=/usr/bin/python3 \
          -DPYTHON_LIBRARY:FILEPATH=${PYTHON_LIBRARY} \
          -DPYTHON_INCLUDE_DIR:PATH=${PYTHON_INCLUDE_DIR} \
          .. && \
          make -j 4 && make install
          
          
          