FROM centos6.10 #AS build

#ENV LANGUAGE=en_US.UTF-8 \
#    LANG=en_US.UTF-8 \
#    LC_ALL=en_US.UTF-8 \
#    LC_CTYPE=en_US.UTF-8

# Replace regular CentOS 6 mirror list with vault.centos.org, as CentOS 6 is EOL
# and regular mirrors aren't hosted any more.
#RUN sed -i 's%^mirrorlist%#mirrorlist%g' /etc/yum.repos.d/* && \
    #sed -i 's%#baseurl=http://mirror.centos.org%baseurl=http://vault.centos.org%g' /etc/yum.repos.d/* && \
    #sed -i 's%#baseurl=http://mirror.centos.org%baseurl=http://vault.centos.org%g' /etc/yum.repos.d/* && \
    # yum makecache fast && \
    # yum clean all    
    
    
#yum -y install gcc pam-devel glibc-devel net-tools tree git zip && \
    






sed -i 's%#baseurl=https://www.getpagespeed.com/files/centos6-epel-eol.repo%g' /etc/yum.repos.d/*