FROM centos6_w_vtk_itk_nlopt
   

ENV ITK_INSTALL_DIR=/opt/itk/
ENV ITK_DIR=${ITK_INSTALL_DIR}/lib/cmake/ITK-4.13/

ENV VTK_INSTALL_DIR=/opt/vtk/
ENV VTK_DIR=${VTK_INSTALL_DIR}/lib/cmake/vtk-9.0/    

#ENV NLOPT_INSTALL_DIR=/opt/nlopt
#ENV NLOPT_DIR=${NLOPT_INSTALL_DIR}/lib/cmake/nlopt/

ENV LD_LIBRARY_PATH=${VTK_INSTALL_DIR}/lib:${ITK_INSTALL_DIR}/lib:${LD_LIBRARY_PATH}

# DEPENDENCIES - COPIED 
ENV GSL=/home/ch155417/moti/gsl/build/lib/libgsl.a
ENV GSLCBLAS=/home/ch155417/moti/gsl/build/lib/libgslcblas.a
ENV GSL_INCLUDE_DIR=/home/ch155417/moti/gsl/build/include
ENV ITKNLOPTOPTIMIZERS_INCLUDE_DIR=/home/ch169807/moti/itkNLOPTOptimizers/src
ENV NLOPT=/home/ch155417/moti/nlopt-2.2/bin/lib/libnlopt.a
ENV NLOPT_DIR=/home/ch155417/moti/nlopt-2.2
ENV TCLAP_INCLUDE_DIR=/home/ch169807/Software/tclap-1.2.1/include
ENV itkNLOPTOptimizersLib=/home/ch169807/moti/itkNLOPTOptimizers/build/libITKNLOPTOptimizers.a
ENV VTK_DIR=/opt/x86_64/pkgs/vtk/current/lib/cmake/vtk-6.1                                                                                               

# DEPENDENCIES - INSTALLED from source
#ENV ITK_DIR=/opt/itk/lib/InsightToolkit/
ENV ITK_DIR=/opt/x86_64/pkgs/itk/3.20.0/gcc-release/lib/InsightToolkit/
#ENV ITK_DIR=/opt/x86_64/pkgs/itk/4.3.1/gcc-release/lib/cmake/ITK-4.3/

RUN yum install -y libuuid-devel

RUN cd /scim && rm -rf build && mkdir build && cd build && mv /scim/CMakeCache.txt /scim/trash && \
    cmake -DGSL=${GSL} -DGSL_INCLUDE_DIR=${GSL} \
    -DGSLCBLAS=${GSLCBLAS} \
    -DGSL_INCLUDE_DIR=${GSL_INCLUDE_DIR} \
    -DITKNLOPTOPTIMIZERS_INCLUDE_DIR=${ITKNLOPTOPTIMIZERS_INCLUDE_DIR} \
    -DITK_DIR=${ITK_DIR} \
    -DNLOPT=${NLOPT} \
    -DNLOPT_DIR:PATH="${NLOPT_DIR}" \
    -DTCLAP_INCLUDE_DIR:PATH=$TCLAP_INCLUDE_DIR \
    -DitkNLOPTOptimizersLib:PATH=$itkNLOPTOptimizersLib \
    -DVTK_DIR:PATH="${VTK_DIR}" .. && \
    make -j 4 && make install 
